env:
  RUBY_VERSION: 2.6
name: Linting & Testing
on: [pull_request]
jobs:
  # rubocop:
  #   name: Rubocop
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #     - name: Bundle
  #       run: bundle install
  #     - name: Run rubocop
  #       run: bundle exec rubocop
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundle
        run: bundle install
      - name: Run rspec
        run: bundle exec rspec
